GET http://localhost:8080/v1/notes

###

POST http://localhost:8080/v1/notes
Content-Type: application/json

{
  "title": "Maciuś",
  "content": "aaaabbbb"
}


###

GET http://localhost:8080/v1/notes/3

###

DELETE http://localhost:8080/v1/notes/3

###

PUT http://localhost:8080/v1/notes/3
Content-Type: application/json

{
  "title": "Zosia",
  "content": "Samosia"
}

###

GET http://localhost:8080/v1/notes/3/history

###

GET http://localhost:8080/v1/notes/3

###

GET http://localhost:8080/v1/notes/3/originalversion

###

GET http://localhost:8080/v1/notes/note/3/version/2


